apt: initialize the g_autofree gchar * vars so that they can be made const (as their purpose is)
Looking into the code, one can see that all g_autofree gchar * vars
(in the apt backend code) hold pointer values that are actually
"final" (const), according to their purpose and usage in the code. So,
it'd be natural to present them as such, whereby we initialize them
and declare const. It'd give clarity for developers and ability to check our
expectations by the compiler, so that more correctness can be guaranteed
after rewriting the code (e.g., choosing another memory auto-management
means without GCCisms, which might be needed on some platforms).

This change just moves the initialization. "const" cannot be added due to
the (artificial) limitations of the implementation details of g_autofree
in Glib. Below is:

* a patch that would add "const";
* then, an example of a compiler error message in such case;
* and the current code from Glib that is the reason.

commit 0c27f4b072508ecd3f840e8d07dc6e143c3c61c3
Author: Ivan Zakharyaschev <imz@altlinux.org>
Date:   Tue Jan 28 14:36:05 2025 +0300

    apt: make clear that all uses of g_autofree gchar * are const pointers

diff --git a/backends/apt/apt-utils.cpp b/backends/apt/apt-utils.cpp
index 002e16b06..2588b20d1 100644
--- a/backends/apt/apt-utils.cpp
+++ b/backends/apt/apt-utils.cpp
@@ -263,8 +263,7 @@ string fetchChangelogData(AptCacheFile &CacheFile,
             GMatchInfo *match_info;
             if (g_regex_match(regexDate, str, G_REGEX_MATCH_ANCHORED, &match_info)) {
                 g_autoptr(GDateTime) dateTime = NULL;
-                g_autofree gchar *date = NULL;
-                date = g_match_info_fetch_named(match_info, "date");
+                g_autofree gchar * const date = g_match_info_fetch_named(match_info, "date");
                 time_t time;
                 g_warn_if_fail(RFC1123StrToTime(date, time));
                 dateTime = g_date_time_new_from_unix_local(time);

An example error message:

../backends/apt/apt-job.cpp:797:82: error: invalid conversion from ‘const void*’ to ‘void*’ [-fpermissive]
  797 |     g_autofree gchar * const current_package_id = m_cache->buildPackageId(currver);
      |                                                                                  ^
      |                                                                                  |
      |                                                                                  const void*

The reason in glib-autocleanups.h:

static inline void
g_autoptr_cleanup_generic_gfree (void *p)
{
  void **pp = (void**)p;
  g_free (*pp);
}

(TODO: request a change to "const void *" in Glib.)