Requires: apt # It provides the stuff needed to run the APT backend
The stuff needed to run the APT backend: the download methods
(/usr/lib*/apt/methods/), conf files (/etc/apt/), and cache dirs
(/var/cache/apt/archives/).

This fixes the error messages like this when trying to use the APT
backend without having apt installed:

    # /usr/lib/packagekit-direct search-detail packagekit; echo $?
    Status: wait
    Status: loading-cache
    Done: 100%

    (packagekit-direct:7251): PackageKit-APTcc-WARNING **: 11:37:53.571: Could not open file /etc/apt/pkgpriorities - open (2 No such file or directory)

    (packagekit-direct:7251): PackageKit-APTcc-WARNING **: 11:37:53.571: could not open package priority file /etc/apt/pkgpriorities
    Error: cannot-get-lock  E: Could not open file /etc/apt/pkgpriorities - open (2 No such file or directory)
    E: could not open package priority file /etc/apt/pkgpriorities

    Status: finished
    Exit code: failed
    0

(cherry picked from commit 55971175a45d74b394eb72fb393f05af005235f8)
(= 1.2.3-alt2~1)